# Generated by Django 2.0.1 on 2018-03-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_preference',
            field=models.CharField(choices=[('none', 'None'), ('email', 'Email')], default='none', max_length=140),
            preserve_default=False,
        ),
    ]
