# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170720_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('admin_project', 'Can admin the project.'), ('view_project', "Can view the project and it's tickets."), ('create_tickets', 'Can create tickets within the project.'), ('edit_tickets', 'Can edit tickets within the project.'), ('delete_tickets', 'Can delete tickets within the project.'), ('add_comments', 'Can comment on tickets within the project.'))},
        ),
    ]
