# Generated by Django 2.0.1 on 2018-03-07 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_auto_20180203_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='watchers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
