# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_value', models.IntegerField()),
                ('str_value', models.CharField(max_length=255)),
                ('opt_value', models.CharField(max_length=255)),
                ('flt_value', models.FloatField()),
                ('date_value', models.DateTimeField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.Field')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tickets.Ticket')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='options',
            field=models.ManyToManyField(to='fields.FieldOption'),
        ),
    ]
