# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='data_type',
            field=models.CharField(choices=[('FLOAT', 'FLOAT'), ('STRING', 'STRING'), ('TEXT', 'TEXT'), ('INTEGER', 'INTEGER'), ('DATE', 'DATE'), ('OPTION', 'OPTION')], max_length=10),
        ),
    ]
