# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvalue',
            name='date_value',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='flt_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='int_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='opt_value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='str_value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
