# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_auto_20170612_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='options',
            field=models.ManyToManyField(blank=True, to='fields.FieldOption'),
        ),
    ]
