# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='projects/icons/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='homepage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
