# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('admin_project', 'Ability to admin the project.'), ('view_project', "Ability to view the project and it's tickets."), ('create_tickets', 'Ability to create tickets within the project.'), ('edit_tickets', 'Ability to edit tickets within the project.'), ('delete_tickets', 'Ability to delete tickets within the project.'), ('comment_tickets', 'Ability to comment on tickets within the project.'))},
        ),
    ]
