language: python
python:
  - "3.5"
  - "3.6"
  - "pypy3"
services:
  - postgres
  - redis
before_script:
  - psql -c 'create database prae_dev;' -U postgres
install:
  - pip install tox
script:
  - tox
