language: python
python:
  - 3.4
  - 3.5
  - 3.6
services:
  - postgresql
  - redis
  - rabbitmq
install:
  - pip install -r requirements.txt
  - pip install -r requirements.dev.txt
before_script:
  - psql -c 'create database praelatus;' -U postgres
  - psql -c "alter role postgres with password 'postgres'" -U postgres
  - python manage.py migrate
script:
  - pylint -j 4 apps/* praelatus
  - python manage.py test