version: '3'
services:
  web:
    build: .
    image: praelatus:dev
    entrypoint: /bin/bash /opt/praelatus/scripts/docker-compose.sh
    depends_on:
      - db
      - redis
    volumes:
      - ".:/opt/praelatus"
      - "/opt/praelatus/node_modules"
      - "data-volume:/opt/praelatus/data"
    env_file: config/docker/envfile
  celery:
    build: .
    image: praelatus-celery:dev
    entrypoint: celery -A praelatus worker -l info
    volumes:
      - ".:/opt/praelatus"
    depends_on:
      - rabbitmq
      - redis
    env_file: config/docker/envfile
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file: config/docker/envfile
    volumes:
      - ".:/opt/praelatus"
      - "/opt/praelatus/node_modules"
      - "data-volume:/opt/praelatus/data"
  redis:
    image: "redis"
  db:
    image: "postgres"
    volumes:
      - "data-volume-db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=praelatus
  rabbitmq:
    image: "rabbitmq"
  nginx:
    image: "nginx"
    depends_on:
      - web
    ports:
      - "8000:80"
    volumes:
      - "./static/:/usr/share/nginx/html/static"
      - "./config/docker/nginx.conf:/etc/nginx/nginx.conf"

volumes:
  data-volume:
    driver: local
  data-volume-db:
    driver: local
