# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
        ('tickets', '0001_initial'),
        ('projects', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_schemes', to='projects.Project')),
                ('ticket_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_schemes', to='tickets.TicketType')),
            ],
        ),
        migrations.CreateModel(
            name='FieldSchemeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.Field')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='schemes.FieldScheme')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_schemes', to='projects.Project')),
                ('ticket_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_schemes', to='tickets.TicketType')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='workflows.Workflow')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='workflowscheme',
            unique_together=set([('project', 'ticket_type', 'workflow')]),
        ),
        migrations.AlterUniqueTogether(
            name='fieldschemefield',
            unique_together=set([('scheme', 'field')]),
        ),
        migrations.AlterUniqueTogether(
            name='fieldscheme',
            unique_together=set([('project', 'ticket_type')]),
        ),
    ]
