# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowscheme',
            name='name',
        ),
        migrations.AlterField(
            model_name='fieldscheme',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
