"""empty message

Revision ID: c3de6b6f6d80
Revises: f3510720bd3c
Create Date: 2017-04-16 20:14:30.368937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3de6b6f6d80'
down_revision = 'f3510720bd3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transitions', sa.Column('workflow_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'transitions', ['name', 'workflow_id'])
    op.create_foreign_key(None, 'transitions', 'workflows', ['workflow_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transitions', type_='foreignkey')
    op.drop_constraint(None, 'transitions', type_='unique')
    op.drop_column('transitions', 'workflow_id')
    # ### end Alembic commands ###
