"""empty message

Revision ID: e991b95da9e8
Revises: 4279a3cd2ef8
Create Date: 2017-04-10 11:11:35.078713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e991b95da9e8'
down_revision = '4279a3cd2ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows_projects',
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflows_projects')
    # ### end Alembic commands ###
