# Generated by Django 2.0.1 on 2018-01-04 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='from_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflows.Status'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='to_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='workflows.Status'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='create_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflows.Status'),
        ),
    ]
