---
- name: rabbitmq_users | creating rabbitmq users
  rabbitmq_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    vhost: "{{ item.vhost }}"
    configure_priv: "{{ item.configure_priv }}"
    read_priv: "{{ item.read_priv }}"
    write_priv: "{{ item.write_priv }}"
    tags: "{{ item.tags }}"
    state: present
  with_items: "{{ rabbitmq_users }}"
