---
- name: redhat | installing pre-reqs
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release

- name: redhat | installing erlang
  yum:
    name: "erlang"
    state: latest

- name: redhat | adding RabbitMQ public GPG key
  rpm_key:
    key: "{{ rabbitmq_redhat_repo_key }}"
    state: present

- name: redhat | downloading RabbitMQ
  get_url:
    url: "{{ rabbitmq_redhat_url }}/{{ rabbitmq_redhat_package }}"
    dest: "/opt/{{ rabbitmq_redhat_package }}"

- name: redhat | installing RabbitMQ
  yum:
    name: "/opt/{{ rabbitmq_redhat_package }}"
    state: present

- name: redhat | starting and enabling RabbitMQ service
  service:
    name: "rabbitmq-server"
    state: started
    enabled: yes
