# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='name',
            field=models.CharField(default='Create', max_length=255),
        ),
    ]
