# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='transition',
        ),
        migrations.DeleteModel(
            name='WebHook',
        ),
    ]
