# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_remove_status_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
