# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_auto_20170612_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='transition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='web_hooks', to='workflows.Transition'),
            preserve_default=False,
        ),
    ]
