# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('hook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hooks.Hook')),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('method', models.CharField(default='POST', max_length=10)),
                ('body', models.TextField(blank=True, null=True)),
            ],
            bases=('hooks.hook',),
        ),
        migrations.AddField(
            model_name='hook',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
