# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "leftB_OPrightU_OPLIST STRING NUMBER DATE B_OP U_OP FIELD COMPAexpression : expression B_OP expressionexpression : U_OP expressionexpression : '(' expression ')' expression : FIELD COMPA valuevalue : STRING\n            | LIST\n            | NUMBER\n            | DATE"

_lr_action_items = {
    '(': ([
        0,
        1,
        2,
        8,
    ], [
        2,
        2,
        2,
        2,
    ]),
    'FIELD': ([
        0,
        1,
        2,
        8,
    ], [
        3,
        3,
        3,
        3,
    ]),
    'LIST': ([
        7,
    ], [
        10,
    ]),
    'B_OP': ([
        4,
        5,
        6,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
    ], [
        8,
        -2,
        8,
        -3,
        -6,
        -5,
        -7,
        -8,
        -4,
        -1,
    ]),
    '$end': ([
        4,
        5,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
    ], [
        0,
        -2,
        -3,
        -6,
        -5,
        -7,
        -8,
        -4,
        -1,
    ]),
    'STRING': ([
        7,
    ], [
        11,
    ]),
    'NUMBER': ([
        7,
    ], [
        12,
    ]),
    'DATE': ([
        7,
    ], [
        13,
    ]),
    'COMPA': ([
        3,
    ], [
        7,
    ]),
    ')': ([
        5,
        6,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
    ], [
        -2,
        9,
        -3,
        -6,
        -5,
        -7,
        -8,
        -4,
        -1,
    ]),
    'U_OP': ([
        0,
        1,
        2,
        8,
    ], [
        1,
        1,
        1,
        1,
    ]),
}

_lr_action = {}
for _k, _v in _lr_action_items.items():
    for _x, _y in zip(_v[0], _v[1]):
        if _x not in _lr_action:
            _lr_action[_x] = {}
        _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {
    'value': ([
        7,
    ], [
        14,
    ]),
    'expression': ([
        0,
        1,
        2,
        8,
    ], [
        4,
        5,
        6,
        15,
    ]),
}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
    for _x, _y in zip(_v[0], _v[1]):
        if _x not in _lr_goto:
            _lr_goto[_x] = {}
        _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
    ("S' -> expression", "S'", 1, None, None, None),
    ('expression -> expression B_OP expression', 'expression', 3,
     'p_expression_b_op', 'dsl.py', 134),
    ('expression -> U_OP expression', 'expression', 2, 'p_expression_u_op',
     'dsl.py', 142),
    ('expression -> ( expression )', 'expression', 3, 'p_expression_paren',
     'dsl.py', 148),
    ('expression -> FIELD COMPA value', 'expression', 3, 'p_expression_ID',
     'dsl.py', 153),
    ('value -> STRING', 'value', 1, 'p_value', 'dsl.py', 159),
    ('value -> LIST', 'value', 1, 'p_value', 'dsl.py', 160),
    ('value -> NUMBER', 'value', 1, 'p_value', 'dsl.py', 161),
    ('value -> DATE', 'value', 1, 'p_value', 'dsl.py', 162),
]
