# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 17:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_tickettype_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tickets.Ticket'),
        ),
    ]
