"""empty message

Revision ID: baaf8ee271a4
Revises: e991b95da9e8
Create Date: 2017-04-10 11:12:16.328479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baaf8ee271a4'
down_revision = 'e991b95da9e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'workflows_projects', ['workflow_id', 'project_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows_projects', type_='unique')
    # ### end Alembic commands ###
