"""empty message

Revision ID: c0723755be7f
Revises: 720fb4e00eff
Create Date: 2017-04-16 15:16:22.228043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0723755be7f'
down_revision = '720fb4e00eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'field_values', ['field_id', 'ticket_id'])
    op.create_unique_constraint(None, 'fields', ['name'])
    op.add_column('tickets', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'projects', ['project_id'], ['id'])
    op.drop_constraint('users_roles_user_id_role_id_key', 'users_roles', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_roles_user_id_role_id_key', 'users_roles', ['user_id', 'role_id'])
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'project_id')
    op.drop_constraint(None, 'fields', type_='unique')
    op.drop_constraint(None, 'field_values', type_='unique')
    # ### end Alembic commands ###
