# Generated by Django 2.0.1 on 2018-01-04 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_auto_20170720_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldscheme',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_schemes', to='tickets.TicketType'),
        ),
        migrations.AlterField(
            model_name='workflowscheme',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_schemes', to='tickets.TicketType'),
        ),
    ]
