---
- name: debian | ensure apt dependencies are installed
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - python3
    - python3-pip
    - libpq-dev
    - git
