# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_auto_20170713_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='last_used',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
