# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='bg_color',
            field=models.CharField(default='#703D6F', max_length=7),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
