- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"

- include: fedora.yml
  when: ansible_distribution == "Fedora"

- include: common.yml
