#!/usr/bin/env python3
# flake8: noqa

import os
import sys
from os.path import dirname
from os.path import join
from os.path import exists

if not exists('src'):
    os.chdir(dirname(dirname(__file__)))

sys.path.append(join(os.getcwd(), 'src'))

import praelatus.cli
praelatus.cli.cli()
