#
# Login
#
POST http://127.0.0.1:8000/api/v1/tokens
Content-Type: application/json
{
	"username": "testadmin",
	"password": "test"
}
#
#
#
PUT http://127.0.0.1:8000/api/v1/projects/TEST
Content-Type: application/json
Authorization: Token eyJpZCI6IDIsICJwcm9maWxlX3BpYyI6ICJodHRwczovL2dyYXZhdGFyLmNvbS9hdmF0YXIvNTU1MDJmNDBkYzhiN2M3Njk4ODBiMTA4NzRhYmM5ZDAiLCAiaXNfYWRtaW4iOiB0cnVlLCAiaXNfYWN0aXZlIjogdHJ1ZSwgImZ1bGxfbmFtZSI6ICJUZXN0IFRlc3RlcnNvbiIsICJ1c2VybmFtZSI6ICJ0ZXN0YWRtaW4iLCAiZW1haWwiOiAidGVzdEBleGFtcGxlLmNvbSJ9LkRBcWNvQS5RV1F6Ml9Yd2lrMV9NX0ZjQi1XQWd6cUNXek0=
{
  "created_date": "2017-05-27 01:07:58.985606",
  "description": null,
  "homepage": null,
  "icon_url": null,
  "id": 1,
  "key": "TEST",
  "lead": {
    "email": "test@example.com",
    "full_name": "Test Testerson II",
    "id": 3,
    "is_active": true,
    "is_admin": false,
    "profile_pic": "https://gravatar.com/avatar/55502f40dc8b7c769880b10874abc9d0",
    "username": "testuser"
  },
  "name": "TEST Project update",
  "repo": null
}
#
# Get ticket types
#
GET http://127.0.0.1:8000/api/v1/ticketTypes
Content-Type: application/json
Authorization: Token eyJpZCI6IDIsICJwcm9maWxlX3BpYyI6ICJodHRwczovL2dyYXZhdGFyLmNvbS9hdmF0YXIvNTU1MDJmNDBkYzhiN2M3Njk4ODBiMTA4NzRhYmM5ZDAiLCAiaXNfYWRtaW4iOiB0cnVlLCAiaXNfYWN0aXZlIjogdHJ1ZSwgImZ1bGxfbmFtZSI6ICJUZXN0IFRlc3RlcnNvbiIsICJ1c2VybmFtZSI6ICJ0ZXN0YWRtaW4iLCAiZW1haWwiOiAidGVzdEBleGFtcGxlLmNvbSJ9LkRBcWNvQS5RV1F6Ml9Yd2lrMV9NX0ZjQi1XQWd6cUNXek0=
#
#
#
GET http://127.0.0.1:8000/api/v1/tickets/TEST-2
Content-Type: application/json
Authorization: Token eyJpZCI6IDIsICJwcm9maWxlX3BpYyI6ICJodHRwczovL2dyYXZhdGFyLmNvbS9hdmF0YXIvNTU1MDJmNDBkYzhiN2M3Njk4ODBiMTA4NzRhYmM5ZDAiLCAiaXNfYWRtaW4iOiB0cnVlLCAiaXNfYWN0aXZlIjogdHJ1ZSwgImZ1bGxfbmFtZSI6ICJUZXN0IFRlc3RlcnNvbiIsICJ1c2VybmFtZSI6ICJ0ZXN0YWRtaW4iLCAiZW1haWwiOiAidGVzdEBleGFtcGxlLmNvbSJ9LkRBcWNvQS5RV1F6Ml9Yd2lrMV9NX0ZjQi1XQWd6cUNXek0=
#
#
#
POST http://127.0.0.1:8000/api/v1/fields
Content-Type: application/json
Authorization: Token eyJpZCI6IDIsICJwcm9maWxlX3BpYyI6ICJodHRwczovL2dyYXZhdGFyLmNvbS9hdmF0YXIvNTU1MDJmNDBkYzhiN2M3Njk4ODBiMTA4NzRhYmM5ZDAiLCAiaXNfYWRtaW4iOiB0cnVlLCAiaXNfYWN0aXZlIjogdHJ1ZSwgImZ1bGxfbmFtZSI6ICJUZXN0IFRlc3RlcnNvbiIsICJ1c2VybmFtZSI6ICJ0ZXN0YWRtaW4iLCAiZW1haWwiOiAidGVzdEBleGFtcGxlLmNvbSJ9LkRBcWNvQS5RV1F6Ml9Yd2lrMV9NX0ZjQi1XQWd6cUNXek0=
{
    "name": "test-update-api",
    "data_type": "STRING"
}
#
#
#
GET http://127.0.0.1:8000/api/v1/workflows
Content-Type: application/json
Authorization: Token eyJpZCI6IDIsICJwcm9maWxlX3BpYyI6ICJodHRwczovL2dyYXZhdGFyLmNvbS9hdmF0YXIvNTU1MDJmNDBkYzhiN2M3Njk4ODBiMTA4NzRhYmM5ZDAiLCAiaXNfYWRtaW4iOiB0cnVlLCAiaXNfYWN0aXZlIjogdHJ1ZSwgImZ1bGxfbmFtZSI6ICJUZXN0IFRlc3RlcnNvbiIsICJ1c2VybmFtZSI6ICJ0ZXN0YWRtaW4iLCAiZW1haWwiOiAidGVzdEBleGFtcGxlLmNvbSJ9LkRBcWNvQS5RV1F6Ml9Yd2lrMV9NX0ZjQi1XQWd6cUNXek0=
#
# Create status
#
GET http://127.0.0.1:8000/api/v1/fields/8
Authorization: Token eyJpZCI6IDIsICJwcm9maWxlX3BpYyI6ICJodHRwczovL2dyYXZhdGFyLmNvbS9hdmF0YXIvNTU1MDJmNDBkYzhiN2M3Njk4ODBiMTA4NzRhYmM5ZDAiLCAiaXNfYWRtaW4iOiB0cnVlLCAiaXNfYWN0aXZlIjogdHJ1ZSwgImZ1bGxfbmFtZSI6ICJUZXN0IFRlc3RlcnNvbiIsICJ1c2VybmFtZSI6ICJ0ZXN0YWRtaW4iLCAiZW1haWwiOiAidGVzdEBleGFtcGxlLmNvbSJ9LkRBcWNvQS5RV1F6Ml9Yd2lrMV9NX0ZjQi1XQWd6cUNXek0=
Content-Type: application/json
#
#
#
POST http://127.0.0.1:8000/api/v1/workflows
Authorization: Token eyJpZCI6IDIsICJwcm9maWxlX3BpYyI6ICJodHRwczovL2dyYXZhdGFyLmNvbS9hdmF0YXIvNTU1MDJmNDBkYzhiN2M3Njk4ODBiMTA4NzRhYmM5ZDAiLCAiaXNfYWRtaW4iOiB0cnVlLCAiaXNfYWN0aXZlIjogdHJ1ZSwgImZ1bGxfbmFtZSI6ICJUZXN0IFRlc3RlcnNvbiIsICJ1c2VybmFtZSI6ICJ0ZXN0YWRtaW4iLCAiZW1haWwiOiAidGVzdEBleGFtcGxlLmNvbSJ9LkRBcWNvQS5RV1F6Ml9Yd2lrMV9NX0ZjQi1XQWd6cUNXek0=
Content-Type: application/json
{
  "name": "Some New Workflow",
  "description": "A simple workflow that fits most use cases.",
  "transitions": {
	"In Progress": [
	  {
		"id": 1,
		"name": "Done",
		"hooks": [],
		"to_status": {
		  "id": 3,
		  "name": "Done"
		}
	  },
	  {
		"id": 2,
		"name": "Backlog",
		"hooks": [],
		"to_status": {
		  "id": 1,
		  "name": "Backlog"
		}
	  }
	],
	"Done": [
	  {
		"id": 3,
		"name": "ReOpen",
		"hooks": [],
		"to_status": {
		  "id": 1,
		  "name": "Backlog"
		}
	  }
	],
	"Backlog": [
	  {
		"id": 5,
		"name": "In Progress",
		"hooks": [],
		"to_status": {
		  "id": 2,
		  "name": "In Progress"
		}
	  }
	],
	"Create": [
	  {
		"id": 4,
		"name": "Create",
		"hooks": [],
		"to_status": {
		  "id": 1,
		  "name": "Backlog"
		}
	  }
	]
  }
}