# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 18:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='query',
            unique_together=set([('owner', 'name')]),
        ),
    ]
