# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 21:31
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.CharField(max_length=140)),
                ('href', models.URLField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='tickets.Ticket')),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
