# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_groups'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='projects',
            field=models.ManyToManyField(related_name='ticket_types', to='projects.Project'),
        ),
    ]
