# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20170610_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='projects.Project'),
        ),
    ]
