# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20170613_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldscheme',
            name='ticket_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_schemes', to='tickets.TicketType'),
        ),
    ]
