# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_watchers'),
        ('tickets', '0003_auto_20170626_2300'),
    ]

    operations = [
    ]
