# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20170614_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowscheme',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_schemes', to='tickets.TicketType'),
        ),
    ]
