# Generated by Django 2.0.1 on 2018-03-07 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20180304_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
